version: "3.8"

services:
  db:
    image: mysql:8.0.32
    container_name: 
    volumes:
      - ./db/conf.d:/etc/mysql/conf.d
      - ./db/initdb.d:/docker-entrypoint-initdb.d
    # volumes:
    #   - /Users/admin/datadir:/var/lib/mysql  
    environment:
      - MYSQL_DATABASE=
      - MYSQL_USER=
      - MYSQL_PASSWORD=
      - MYSQL_ROOT_PASSWORD=root
      - TZ=Asia/Seoul
    ports:
      - "3306:3306"
    platform: linux/arm64/v8
