version: "3.8"

services:
  db:
    image: postgres:latest
    container_name: 
    environment:
      POSTGRES_DB: 
      POSTGRES_USER: 
      POSTGRES_PASSWORD: 
    ports:
      - "5432:5432"
    volumes:
      - ./db/conf.d:/var/lib/postgresql/data
